- name: 禁用SELinux
  selinux:
     state: disabled

- name: 关闭防火墙
  service:
      name: firewalld
      state: stopped
      enabled: False

- sysctl:
    name: fs.file-max
    value: 999999
    sysctl_set: yes
    state: present
    reload: yes      

- sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 600
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 30
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 5000
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.ipv4.ip_local_port_range
    value: 1024 61000
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.ipv4.tcp_rmem
    value: 4096  32768 262142
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.ipv4.tcp_wmem
    value: 4096  32768 262142
    sysctl_set: yes
    state: present
    reload: yes      

- sysctl:
    name: net.core.netdev_max_backlog
    value: 8096
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.core.rmem_default
    value: 262144
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.core.wmem_default
    value: 262144
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.core.rmem_max
    value: 2097152
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.core.wmem_max
    value: 2097152
    sysctl_set: yes
    state: present
    reload: yes  

- sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    sysctl_set: yes
    state: present
    reload: yes  
