- name: 安装EPEL源
  yum: name=epel-release state=latest  

- name: 安装开发者工具包
  yum: name='@Development Tools' state=latest  

- name: 安装常用工具
  yum: name='{{item.pkg}}' state=latest  
  with_items:
      - {pkg: 'git'}
      - {pkg: 'htop'}
      - {pkg: 'wget'}
      - {pkg: 'net-tools'}

- name: 安装Supervisor
  yum: name='supervisor' state=latest 
  notify: enable-supervisor